### ISSUE TITLE
About Video call

### ISSUE THREAD

**Issue by jackie-jiang-ios** [boostlingo/boostlingo-ios#3]
We need to test the receiver and speaker modes for video calls
And We find Video call switch to receiver invalid, Please Help me
My Email is jackie.jiang@transn.com

**Comment by dkornev** [comment]
Hi @hold-my-hand 
Could you please provide more details about the issue. How do you switch between the receiver and speaker modes? What iPhone device are you using and what iOS it's running?

**Comment by jackie-jiang-ios** [comment]
@implementation AVAudioSession (Extension)
///methoh 1
- (BOOL)switchSpeaker:(BOOL)onOrOff
{
    NSError* audioError = nil;
    BOOL changeResult = NO;
    
    if (@available(iOS 13.0, *)) {
        [self setAllowHapticsAndSystemSoundsDuringRecording:YES error:nil];
    } else {
        
    }
    if (onOrOff == YES)
    {
       
        changeResult = [self overrideOutputAudioPort:AVAudioSessionPortOverrideSpeaker
                                                                          error:&audioError];
        if (!changeResult && self.categoryOptions != (AVAudioSessionCategoryOptionAllowBluetooth|AVAudioSessionCategoryOptionDefaultToSpeaker)) {
            changeResult = [self setCategory:AVAudioSessionCategoryPlayAndRecord withOptions:AVAudioSessionCategoryOptionAllowBluetooth|AVAudioSessionCategoryOptionDefaultToSpeaker error:&audioError];
            changeResult = [self overrideOutputAudioPort:AVAudioSessionPortOverrideSpeaker
                                                   error:&audioError];
            changeResult = [self setActive:YES error:&audioError];
        }
    }
    else
    {
        AVAudioSessionPortDescription* builtinPort = [self builtinAudioDevice];
        changeResult = [self setPreferredInput:builtinPort
                                            error:&audioError];
    }
    //    [session setMode:AVAudioSessionModeMeasurement error:&audioError];
    return changeResult;
}



- (AVAudioSessionPortDescription*)builtinAudioDevice
{
    NSArray* builtinRoutes = @[AVAudioSessionPortBuiltInMic];
    return [self audioDeviceFromTypes:builtinRoutes];
}
- (AVAudioSessionPortDescription*)audioDeviceFromTypes:(NSArray*)types
{
    NSArray* routes = [self availableInputs];
    for (AVAudioSessionPortDescription* route in routes)
       {
           if ([types containsObject:route.portType])
           {
               return route;
           }
       }
    return nil;
}


///methoh 2
   open class BoostlingoSwift:NSObject{
    @objc public func toggleAudioRoute(speaker:Bool){
            self.boostlingo?.toggleAudioRoute(toSpeaker: speaker) 
    }

We tried many ways and no effect

My device is iPhone X iOS 13.4.5

**Comment by jackie-jiang-ios** [comment]
(lldb) po self.mj_keyValues
{
    allowHapticsAndSystemSoundsDuringRecording = 1;
    availableCategories =     (
        AVAudioSessionCategoryAmbient,
        AVAudioSessionCategorySoloAmbient,
        AVAudioSessionCategoryPlayback,
        AVAudioSessionCategoryRecord,
        AVAudioSessionCategoryPlayAndRecord,
        AVAudioSessionCategoryMultiRoute
    );
    availableInputs =     (
                {
            UID = "Built-In Microphone";
            dataSources =             (
                                {
                    dataSourceID = 1835216946;
                    dataSourceName = "\U524d";
                    location = Upper;
                    orientation = Front;
                    selectedPolarPattern = Omnidirectional;
                    supportedPolarPatterns =                     (
                        Cardioid,
                        Cardioid
                    );
                },
                                {
                    dataSourceID = 1835216947;
                    dataSourceName = "\U8fd4\U56de";
                    location = Upper;
                    orientation = Back;
                    selectedPolarPattern = Subcardioid;
                    supportedPolarPatterns =                     (
                        Subcardioid
                    );
                }
            );
            hasHardwareVoiceCallProcessing = 0;
            portName = "iPhone \U9ea6\U514b\U98ce";
            portType = MicrophoneBuiltIn;
            selectedDataSource =             {
                dataSourceID = 1835216947;
                dataSourceName = "\U8fd4\U56de";
                location = Upper;
                orientation = Back;
                selectedPolarPattern = Subcardioid;
                supportedPolarPatterns =                 (
                    Subcardioid
                );
            };
        }
    );
    availableModes =     (
        AVAudioSessionModeDefault,
        AVAudioSessionModeVoiceChat,
        AVAudioSessionModeVideoRecording,
        AVAudioSessionModeMeasurement,
        AVAudioSessionModeMoviePlayback,
        AVAudioSessionModeVideoChat,
        AVAudioSessionModeSpokenAudio,
        AVAudioSessionModeVoicePrompt
    );
    category = AVAudioSessionCategoryPlayAndRecord;
    categoryOptions = 4;
    currentRoute =     {
        inputs =         (
                        {
                UID = "Built-In Microphone";
                channels =                 (
                                        {
                        channelLabel = 0;
                        channelName = "iPhone \U9ea6\U514b\U98ce 1";
                        channelNumber = 1;
                        owningPortUID = "Built-In Microphone";
                    },
                                        {
                        channelLabel = 0;
                        channelName = "iPhone \U9ea6\U514b\U98ce 2";
                        channelNumber = 2;
                        owningPortUID = "Built-In Microphone";
                    },
                                        {
                        channelLabel = 0;
                        channelName = "iPhone \U9ea6\U514b\U98ce 3";
                        channelNumber = 3;
                        owningPortUID = "Built-In Microphone";
                    },
                                        {
                        channelLabel = 0;
                        channelName = "iPhone \U9ea6\U514b\U98ce 4";
                        channelNumber = 4;
                        owningPortUID = "Built-In Microphone";
                    }
                );
                dataSources =                 (
                                        {
                        dataSourceID = 1835216946;
                        dataSourceName = "\U524d";
                        location = Upper;
                        orientation = Front;
                        selectedPolarPattern = Omnidirectional;
                        supportedPolarPatterns =                         (
                            Cardioid,
                            Cardioid
                        );
                    },
                                        {
                        dataSourceID = 1835216947;
                        dataSourceName = "\U8fd4\U56de";
                        location = Upper;
                        orientation = Back;
                        selectedPolarPattern = Subcardioid;
                        supportedPolarPatterns =                         (
                            Subcardioid
                        );
                    }
                );
                hasHardwareVoiceCallProcessing = 0;
                portName = "iPhone \U9ea6\U514b\U98ce";
                portType = MicrophoneBuiltIn;
                selectedDataSource =                 {
                    dataSourceID = 1835216947;
                    dataSourceName = "\U8fd4\U56de";
                    location = Upper;
                    orientation = Back;
                    selectedPolarPattern = Subcardioid;
                    supportedPolarPatterns =                     (
                        Subcardioid
                    );
                };
            }
        );
        outputs =         (
                        {
                UID = Speaker;
                channels =                 (
                                        {
                        channelLabel = 4294967295;
                        channelName = "\U626c\U58f0\U5668 1";
                        channelNumber = 1;
                        owningPortUID = Speaker;
                    },
                                        {
                        channelLabel = 4294967295;
                        channelName = "\U626c\U58f0\U5668 2";
                        channelNumber = 2;
                        owningPortUID = Speaker;
                    }
                );
                dataSources =                 (
                );
                hasHardwareVoiceCallProcessing = 0;
                portName = "\U626c\U58f0\U5668";
                portType = Speaker;
            }
        );
        siriInputSource = 1936289391;
        siriRemoteInputIdentifier = "";
        supportsDoAP = 0;
        supportsSoftwareVolume = 0;
    };
    isPrimary = 1;
    mode = AVAudioSessionModeVideoChat;
    otherAudioPlaying = 0;
    preferredInput =     {
        UID = "Built-In Microphone";
        dataSources =         (
                        {
                dataSourceID = 1835216946;
                dataSourceName = "\U524d";
                location = Upper;
                orientation = Front;
                selectedPolarPattern = Omnidirectional;
                supportedPolarPatterns =                 (
                    Cardioid,
                    Cardioid
                );
            },
                        {
                dataSourceID = 1835216947;
                dataSourceName = "\U8fd4\U56de";
                location = Upper;
                orientation = Back;
                selectedPolarPattern = Subcardioid;
                supportedPolarPatterns =                 (
                    Subcardioid
                );
            }
        );
        hasHardwareVoiceCallProcessing = 0;
        portName = "iPhone \U9ea6\U514b\U98ce";
        portType = MicrophoneBuiltIn;
        selectedDataSource =         {
            dataSourceID = 1835216947;
            dataSourceName = "\U8fd4\U56de";
            location = Upper;
            orientation = Back;
            selectedPolarPattern = Subcardioid;
            supportedPolarPatterns =             (
                Subcardioid
            );
        };
    };
    promptStyle = 1936224884;
    recordPermission = 1735552628;
    routeSharingPolicy = 0;
    secondaryAudioShouldBeSilencedHint = 0;
}

When video Call is ON ,this is the AVAudioSesstion's key and values

**Comment by dkornev** [comment]
Right now switching between speakers is not supported for video calls. We will try to add the support in the next release which we're working on already

**Comment by jackie-jiang-ios** [comment]
ok, I see

**Comment by dkornev** [comment]
Let's keep it open until it's fixed
